services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000" # Frontend
      - "3001:3001" # Backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - db
    command: npm run dev:docker

volumes:
  postgres_data: